name: workflow for development branch

on:
  pull_request:
  workflow_dispatch:

jobs:
  analyze-job:
    if: !startsWith(github.head_ref , 'releases/')
    uses: ./.github/workflows/analyze.job.yaml
    secrets: inherit
  test-job:
    if: !startsWith(github.head_ref , 'releases/')
    uses: ./.github/workflows/test.job.yaml
    secrets: inherit
